// <auto-generated />
namespace MVCPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addfirstandlastnamefieldstouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addfirstandlastnamefieldstouser));
        
        string IMigrationMetadata.Id
        {
            get { return "202205031947388_Add first and last name fields to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
